# Generated by Django 5.2.10 on 2026-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
        migrations.AddField(
            model_name='trainer',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
