# Generated by Django 5.2.10 on 2026-03-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_remove_trainer_course_trainer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='category',
        ),
    ]
