# Generated by Django 5.2.10 on 2026-03-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_remove_trainer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danceapp.courses'),
        ),
    ]
