# Generated by Django 5.2.10 on 2026-03-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0004_trainer_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_joined_institution',
            field=models.BooleanField(default=False),
        ),
    ]
