# Generated by Django 5.2.10 on 2026-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0005_user_is_joined_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininstitution',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
