# Generated by Django 5.2.10 on 2026-03-18 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0007_reel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_marked', models.TimeField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='danceapp.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
