# Generated by Django 5.2.10 on 2026-03-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0011_remove_product_shop_product_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumebooking',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='security_deposit',
        ),
    ]
