# Generated by Django 5.2.10 on 2026-03-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0013_bookingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
