# Generated by Django 5.2.10 on 2026-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0014_alter_costumebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
