# Generated by Django 5.2.10 on 2026-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0015_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumebooking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
