# Generated by Django 5.2.13 on 2026-04-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0016_costumebooking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
